export default interface User {
    username: string,
    profile_picture: string,
    bio: string,
    followers_count: number,
    following_count: number,
    post_count: number,
    is_verified: boolean,
    is_private: boolean,
    website: string,
    phone_number: string,
    birthdate: Date,
    location: string,
    interests: string,
    story_views: number,
    tagged_users: string,
    engagement_rate: number,
    profile_views: number,
    caption: string,
    hashtags: string,
    comments_count: number
}